spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
